import { ModuleGraph } from "@/backend/types";

export const correctnessInfo: { [key: string]: boolean } = {
  "Core PostgreSQL Engine": true,
  "Query Execution Engine": true,
  "Transaction Management System": false,
  "Extension Support Framework": false,
  "Live Query System": true,
  "Vector Processing Module": false,
  "Filesystem Abstraction Layer": false,
  "Web Worker Management": true,
  "Type Conversion and Serialization": true,
  "Multi-backend Storage System": false,
  "SQL Parsing and Execution Pipeline": true,
  "REPL (Read-Eval-Print Loop) Interface": false,
  "Framework Integration Hooks (React, Vue)": true,
  "Synchronization System": false,
  "Benchmarking Suite": true,
  "PostgreSQL Protocol Implementation": true,
  "In-browser Data Persistence": false,
  "Full-text Search Capability": true,
  "Large Object Support": true,
};

export const sampleModuleGraph: ModuleGraph = {
  "Core PostgreSQL Engine": [
    "Query Execution Engine",
    "Transaction Management System",
    "Extension Support Framework",
    "Live Query System",
    "Vector Processing Module",
    "Filesystem Abstraction Layer",
    "Web Worker Management",
    "Type Conversion and Serialization",
    "Multi-backend Storage System",
    "SQL Parsing and Execution Pipeline",
    "REPL (Read-Eval-Print Loop) Interface",
    "Framework Integration Hooks (React, Vue)",
    "Synchronization System",
    "Benchmarking Suite",
    "PostgreSQL Protocol Implementation",
    "In-browser Data Persistence",
    "Full-text Search Capability",
    "Large Object Support",
  ],
  "Query Execution Engine": [],
  "Live Query System": [
    "Vector Processing Module",
    "Filesystem Abstraction Layer",
    "Web Worker Management",
  ],
  "Vector Processing Module": [],
  "Filesystem Abstraction Layer": [],
  "Web Worker Management": [],
  "Framework Integration Hooks (React, Vue)": [
    "Synchronization System",
    "Benchmarking Suite",
    "PostgreSQL Protocol Implementation",
    "In-browser Data Persistence",
  ],
  "Synchronization System": [],

  "PostgreSQL Protocol Implementation": [],
  "In-browser Data Persistence": [
    "Full-text Search Capability",
    "Large Object Support",
  ],
};
